### ISSUE TITLE
[🐞 BUG]Colored Pill not Working

### ISSUE THREAD

**Issue by Muteplayer** [Magisk-Modules-Alt-Repo/CustomizedNavbar#2]
I installed the module and check only colored navbar (Android 13 AOSP btw), and instaler said it detect overlay on vendor image (if it is an app there is nothing), when I rebooted Pill is not colored as you can see:
![Screenshot Pill](https://user-images.githubusercontent.com/107940851/194171592-f67c0d1c-aa71-47a6-930e-b2ca9d604124.png)

If need logs please tell me.

**Comment by PycmShoma** [comment]
Hi.
Try this version
[CustomizedNavbar_v.3.2.zip](https://github.com/Magisk-Modules-Alt-Repo/CustomizedNavbar/files/9727013/CustomizedNavbar_v.3.2.zip)

**Comment by PycmShoma** [comment]
Fixed. Update released
