### ISSUE TITLE
Module doesn't work at all

### ISSUE THREAD

**Issue by SimplesOne** [Magisk-Modules-Alt-Repo/CustomizedNavbar#5]
At first I thought it got bigger but didn't notice, then I edited it to be even bigger, nothing changed, I have a Samsung A12 and running latest Magisk version. The install was completely succesful.

**Comment by PycmShoma** [comment]
OneUI or AOSP?
Can you provide framework-res.apk and SystemUI.apk files?

**Comment by SimplesOne** [comment]
I did find framework res
[framework-res.zip](https://github.com/Magisk-Modules-Alt-Repo/CustomizedNavbar/files/10216406/framework-res.zip)
I have the stock rom so I guess it's OneUI
[SystemUI.zip](https://github.com/Magisk-Modules-Alt-Repo/CustomizedNavbar/files/10216453/SystemUI.zip)

**Comment by PycmShoma** [comment]
Without the files, I won't be able to see exactly what changes your vendor has made. 
Although it is worth noting that even if I look at them, it is already clear that the resources have been changed. This module is universal for AOSP and works on some other UI's where the vendor did not change the navbar resources.
I have no plans to make a module separately for Samsung.
