### ISSUE TITLE
Not an issue, just wanted to ask...

### ISSUE THREAD

**Issue by Shrtej** [Magisk-Modules-Alt-Repo/CustomizedNavbar#6]
weather the latest version of this i.e. 3.2 compatible with Android 10?

**Comment by PycmShoma** [comment]
Hi.
Use version 1.x for A10

**Comment by Shrtej** [comment]
How can I change the width, length, colour, etc. Through termux or an apk ? Or any other way?

**Comment by PycmShoma** [comment]
The source code is open.  See what resources are responsible for this and change them in overlays by decompiling.  Use apktool for android.  I don't use termux.

**Comment by Shrtej** [comment]
Too complex for a amateur like me, I'll stick to the basics, thx for the
help tho <3

**Comment by PycmShoma** [comment]
Use Apktool M https://maximoff.su/apktool/?lang=en
It is the most advanced apktool for android today. All instructions can be found on the website.

**Comment by Shrtej** [comment]
Eureka!
