### ISSUE TITLE
Could customizations be added for the button navigation bars?

### ISSUE THREAD

**Issue by devycarol** [Magisk-Modules-Alt-Repo/CustomizedNavbar#8]
I saw a different issue on a similar topic that was asking about a specific potential tweak. I have a (hopefully) more general question: could this module be expanded or another module created to customize the AOSP button navigation bars? I often find myself wishing I could:
- Add buttons—I've always wished I could have something like the old menu button in place of the recents button for the two-button layout
- Change the button icons
- Change (and force) the background color and opacity
- Have a top separator for dark mode like there is with light mode
- Have custom actions for things like long-presses or pressing multiple buttons
- Remove the corner-rounding of the tapped-button hints

That's obviously a lot of things, but something I'd honestly be down to do if I ever learn how to code these modules. Could it be done for AOSP-based ROMs? I know it used to have a lot more customization options via the system UI tuner.

**Comment by PycmShoma** [comment]
No buttons. Sorry
